_base_ = './lvis_r101.py'
model = {'_delete_': True,
 'backbone': {'depth': 101,
              'frozen_stages': 1,
              'norm_cfg': {'requires_grad': True, 'type': 'BN'},
              'norm_eval': True,
              'num_stages': 4,
              'out_indices': (0, 1, 2, 3),
              'style': 'pytorch',
              'type': 'ResNet'},
 'data_preprocessor': {'bgr_to_rgb': True,
                       'mean': [123.675, 116.28, 103.53],
                       'pad_mask': True,
                       'pad_size_divisor': 32,
                       'std': [58.395, 57.12, 57.375],
                       'type': 'DetDataPreprocessor'},
 'neck': {'in_channels': [256, 512, 1024, 2048],
          'num_outs': 5,
          'out_channels': 256,
          'type': 'FPN'},
 'roi_head': {'bbox_head': {'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                           'target_stds': [0.1, 0.1, 0.2, 0.2],
                                           'type': 'DeltaXYWHBBoxCoder'},
                            'cls_predictor_cfg': {'tempearture': 20, 'type': 'NormedLinear'},
                            'fc_out_channels': 1024,
                            'in_channels': 256,
                            'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                            'loss_cls': {'loss_weight': 1.0,
                                         'type': 'CrossEntropyLoss',
                                         'use_sigmoid': False},
                            'num_classes': 1203,
                            'reg_class_agnostic': False,
                            'roi_feat_size': 7,
                            'type': 'Shared2FCBBoxHead'},
              'bbox_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                     'out_channels': 256,
                                     'roi_layer': {'output_size': 7,
                                                   'sampling_ratio': 0,
                                                   'type': 'RoIAlign'},
                                     'type': 'SingleRoIExtractor'},
              'mask_head': {'conv_out_channels': 256,
                            'in_channels': 256,
                            'loss_mask': {'loss_weight': 1.0,
                                          'type': 'CrossEntropyLoss',
                                          'use_mask': True},
                            'num_classes': 1203,
                            'num_convs': 4,
                            'predictor_cfg': {'tempearture': 20, 'type': 'NormedConv2d'},
                            'type': 'FCNMaskHead',
                            'upsample_cfg': {'compressed_channels': 64,
                                             'encoder_dilation': 1,
                                             'encoder_kernel': 3,
                                             'scale_factor': 2,
                                             'type': 'carafe',
                                             'up_group': 1,
                                             'up_kernel': 5}},
              'mask_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                     'out_channels': 256,
                                     'roi_layer': {'output_size': 14,
                                                   'sampling_ratio': 0,
                                                   'type': 'RoIAlign'},
                                     'type': 'SingleRoIExtractor'},
              'type': 'StandardRoIHead'},
 'rpn_head': {'anchor_generator': {'ratios': [0.5, 1.0, 2.0],
                                   'scales': [8],
                                   'strides': [4, 8, 16, 32, 64],
                                   'type': 'AnchorGenerator'},
              'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                             'target_stds': [1.0, 1.0, 1.0, 1.0],
                             'type': 'DeltaXYWHBBoxCoder'},
              'feat_channels': 256,
              'in_channels': 256,
              'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
              'loss_cls': {'loss_weight': 1.0, 'type': 'CrossEntropyLoss', 'use_sigmoid': True},
              'type': 'RPNHead'},
 'test_cfg': {'rcnn': {'mask_thr_binary': 0.5,
                       'max_per_img': 300,
                       'nms': {'iou_threshold': 0.5, 'type': 'nms'},
                       'perclass_nms': True,
                       'score_thr': 0.0001},
              'rpn': {'max_per_img': 1000,
                      'min_bbox_size': 0,
                      'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                      'nms_pre': 1000}},
 'train_cfg': {'rcnn': {'assigner': {'ignore_iof_thr': -1,
                                     'match_low_quality': True,
                                     'min_pos_iou': 0.5,
                                     'neg_iou_thr': 0.5,
                                     'pos_iou_thr': 0.5,
                                     'type': 'MaxIoUAssigner'},
                        'debug': False,
                        'mask_size': 28,
                        'pos_weight': -1,
                        'sampler': {'add_gt_as_proposals': True,
                                    'neg_pos_ub': -1,
                                    'num': 512,
                                    'pos_fraction': 0.25,
                                    'type': 'RandomSampler'}},
               'rpn': {'allowed_border': -1,
                       'assigner': {'ignore_iof_thr': -1,
                                    'match_low_quality': True,
                                    'min_pos_iou': 0.3,
                                    'neg_iou_thr': 0.3,
                                    'pos_iou_thr': 0.7,
                                    'type': 'MaxIoUAssigner'},
                       'debug': False,
                       'pos_weight': -1,
                       'sampler': {'add_gt_as_proposals': False,
                                   'neg_pos_ub': -1,
                                   'num': 256,
                                   'pos_fraction': 0.5,
                                   'type': 'RandomSampler'}},
               'rpn_proposal': {'max_per_img': 1000,
                                'min_bbox_size': 0,
                                'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                                'nms_pre': 2000}},
 'type': 'MaskRCNN'}
work_dir = 'work_dirs/lvis_r101_baseline'
