# CALE inference configuration; frozen checkpoint, no detector retraining.
custom_imports = {'imports': ['cale'], 'allow_failed_imports': False}

default_scope = 'mmdet'

model = {'backbone': {'base_width': 4,
              'depth': 101,
              'frozen_stages': 1,
              'groups': 32,
              'init_cfg': None,
              'norm_cfg': {'requires_grad': True, 'type': 'BN'},
              'norm_eval': True,
              'num_stages': 4,
              'out_indices': (0, 1, 2, 3),
              'style': 'pytorch',
              'type': 'ResNeXt'},
 'data_preprocessor': {'bgr_to_rgb': True,
                       'mean': [123.675, 116.28, 103.53],
                       'pad_mask': True,
                       'pad_size_divisor': 32,
                       'std': [58.395, 57.12, 57.375],
                       'type': 'DetDataPreprocessor'},
 'neck': {'in_channels': [256, 512, 1024, 2048],
          'num_outs': 5,
          'out_channels': 256,
          'type': 'FPN'},
 'roi_head': {'bbox_head': {'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                           'target_stds': [0.1, 0.1, 0.2, 0.2],
                                           'type': 'DeltaXYWHBBoxCoder'},
                            'fc_out_channels': 1024,
                            'in_channels': 256,
                            'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                            'loss_cls': {'loss_weight': 1.0,
                                         'type': 'CrossEntropyLoss',
                                         'use_sigmoid': True},
                            'num_classes': 1203,
                            'reg_class_agnostic': False,
                            'roi_feat_size': 7,
                            'type': 'Shared2FCCALEBBoxHead',
                            'frequency_file': 'stat_files/lvis_frequency.csv',
                            'prior_file': 'stat_files/lvis_lacunarity.csv',
                            'eta': 0.8,
                            'gamma': 2.0},
              'bbox_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                     'out_channels': 256,
                                     'roi_layer': {'output_size': 7,
                                                   'sampling_ratio': 0,
                                                   'type': 'RoIAlign'},
                                     'type': 'SingleRoIExtractor'},
              'mask_head': {'conv_out_channels': 256,
                            'in_channels': 256,
                            'loss_mask': {'loss_weight': 1.0,
                                          'type': 'CrossEntropyLoss',
                                          'use_mask': True},
                            'num_classes': 1203,
                            'num_convs': 4,
                            'type': 'FCNMaskHead'},
              'mask_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                     'out_channels': 256,
                                     'roi_layer': {'output_size': 14,
                                                   'sampling_ratio': 0,
                                                   'type': 'RoIAlign'},
                                     'type': 'SingleRoIExtractor'},
              'type': 'StandardRoIHead'},
 'rpn_head': {'anchor_generator': {'ratios': [0.5, 1.0, 2.0],
                                   'scales': [8],
                                   'strides': [4, 8, 16, 32, 64],
                                   'type': 'AnchorGenerator'},
              'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                             'target_stds': [1.0, 1.0, 1.0, 1.0],
                             'type': 'DeltaXYWHBBoxCoder'},
              'feat_channels': 256,
              'in_channels': 256,
              'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
              'loss_cls': {'loss_weight': 1.0, 'type': 'CrossEntropyLoss', 'use_sigmoid': True},
              'type': 'RPNHead'},
 'test_cfg': {'rcnn': {'mask_thr_binary': 0.5,
                       'max_per_img': 300,
                       'nms': {'iou_threshold': 0.5, 'type': 'nms'},
                       'perclass_nms': True,
                       'score_thr': 0.0001},
              'rpn': {'max_per_img': 1000,
                      'min_bbox_size': 0,
                      'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                      'nms_pre': 1000}},
 'train_cfg': {'rcnn': {'assigner': {'ignore_iof_thr': -1,
                                     'match_low_quality': True,
                                     'min_pos_iou': 0.5,
                                     'neg_iou_thr': 0.5,
                                     'pos_iou_thr': 0.5,
                                     'type': 'MaxIoUAssigner'},
                        'debug': False,
                        'mask_size': 28,
                        'pos_weight': -1,
                        'sampler': {'add_gt_as_proposals': True,
                                    'neg_pos_ub': -1,
                                    'num': 512,
                                    'pos_fraction': 0.25,
                                    'type': 'RandomSampler'}},
               'rpn': {'allowed_border': -1,
                       'assigner': {'ignore_iof_thr': -1,
                                    'match_low_quality': True,
                                    'min_pos_iou': 0.3,
                                    'neg_iou_thr': 0.3,
                                    'pos_iou_thr': 0.7,
                                    'type': 'MaxIoUAssigner'},
                       'debug': False,
                       'pos_weight': -1,
                       'sampler': {'add_gt_as_proposals': False,
                                   'neg_pos_ub': -1,
                                   'num': 256,
                                   'pos_fraction': 0.5,
                                   'type': 'RandomSampler'}},
               'rpn_proposal': {'max_per_img': 1000,
                                'min_bbox_size': 0,
                                'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                                'nms_pre': 2000}},
 'type': 'MaskRCNN'}

test_cfg = {'type': 'TestLoop'}

env_cfg = {'cudnn_benchmark': False,
 'mp_cfg': {'mp_start_method': 'fork', 'opencv_num_threads': 0},
 'dist_cfg': {'backend': 'nccl'}}

default_hooks = {'timer': {'type': 'IterTimerHook'}, 'logger': {'type': 'LoggerHook', 'interval': 50}}

log_processor = {'type': 'LogProcessor', 'window_size': 50, 'by_epoch': False}

launcher = 'none'

log_level = 'INFO'

test_dataloader = {'batch_size': 2,
 'dataset': {'ann_file': 'lvis_v1_val.json',
             'backend_args': None,
             'data_prefix': {'img': ''},
             'data_root': 'data/lvis/',
             'pipeline': [{'type': 'LoadImageFromFile'},
                          {'keep_ratio': True, 'scale': (1333, 800), 'type': 'Resize'},
                          {'type': 'LoadAnnotations', 'with_bbox': True, 'with_mask': True},
                          {'meta_keys': ('img_id',
                                         'img_path',
                                         'ori_shape',
                                         'img_shape',
                                         'scale_factor'),
                           'type': 'PackDetInputs'}],
             'test_mode': True,
             'type': 'LVISV1Dataset'},
 'drop_last': False,
 'num_workers': 2,
 'persistent_workers': True,
 'sampler': {'shuffle': False, 'type': 'DefaultSampler'}}

test_evaluator = {'type': 'LVISMetric',
 'ann_file': 'data/lvis/lvis_v1_val.json',
 'metric': ['bbox', 'segm'],
 'format_only': False,
 'outfile_prefix': 'work_dirs/lvis_x101_32/predictions'}

work_dir = 'work_dirs/lvis_x101_32'
