_base_ = './v3det_cascade.py'
model = {'_delete_': True,
 'backbone': {'depth': 50,
              'frozen_stages': 1,
              'init_cfg': None,
              'norm_cfg': {'requires_grad': True, 'type': 'BN'},
              'norm_eval': True,
              'num_stages': 4,
              'out_indices': (0, 1, 2, 3),
              'style': 'pytorch',
              'type': 'SE_ResNet',
              'use_gumbel': True},
 'data_preprocessor': {'bgr_to_rgb': True,
                       'mean': [123.675, 116.28, 103.53],
                       'pad_size_divisor': 32,
                       'std': [58.395, 57.12, 57.375],
                       'type': 'DetDataPreprocessor'},
 'neck': {'in_channels': [256, 512, 1024, 2048],
          'num_outs': 5,
          'out_channels': 256,
          'type': 'FPN'},
 'roi_head': {'bbox_head': [{'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                            'target_stds': [0.1, 0.1, 0.2, 0.2],
                                            'type': 'DeltaXYWHBBoxCoder'},
                             'cls_predictor_cfg': {'s_trainable': False, 'type': 'WCLinear'},
                             'fc_out_channels': 1024,
                             'in_channels': 256,
                             'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                             'loss_cls': {'loss_weight': 1.0,
                                          'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False},
                             'num_classes': 13204,
                             'reg_class_agnostic': True,
                             'roi_feat_size': 7,
                             'type': 'Shared2FCBBoxHead'},
                            {'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                            'target_stds': [0.05, 0.05, 0.1, 0.1],
                                            'type': 'DeltaXYWHBBoxCoder'},
                             'cls_predictor_cfg': {'s_trainable': False, 'type': 'WCLinear'},
                             'fc_out_channels': 1024,
                             'in_channels': 256,
                             'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                             'loss_cls': {'loss_weight': 1.0,
                                          'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False},
                             'num_classes': 13204,
                             'reg_class_agnostic': True,
                             'roi_feat_size': 7,
                             'type': 'Shared2FCBBoxHead'},
                            {'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                            'target_stds': [0.033, 0.033, 0.067, 0.067],
                                            'type': 'DeltaXYWHBBoxCoder'},
                             'cls_predictor_cfg': {'s_trainable': False, 'type': 'WCLinear'},
                             'fc_out_channels': 1024,
                             'in_channels': 256,
                             'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                             'loss_cls': {'loss_weight': 1.0,
                                          'type': 'CrossEntropyLoss',
                                          'use_sigmoid': False},
                             'num_classes': 13204,
                             'reg_class_agnostic': True,
                             'roi_feat_size': 7,
                             'type': 'Shared2FCBBoxHead'}],
              'bbox_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                     'out_channels': 256,
                                     'roi_layer': {'output_size': 7,
                                                   'sampling_ratio': 0,
                                                   'type': 'RoIAlign'},
                                     'type': 'SingleRoIExtractor'},
              'num_stages': 3,
              'stage_loss_weights': [1, 0.5, 0.25],
              'type': 'CascadeRoIHead'},
 'rpn_head': {'anchor_generator': {'ratios': [0.5, 1.0, 2.0],
                                   'scales': [8],
                                   'strides': [4, 8, 16, 32, 64],
                                   'type': 'AnchorGenerator'},
              'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                             'target_stds': [1.0, 1.0, 1.0, 1.0],
                             'type': 'DeltaXYWHBBoxCoder'},
              'feat_channels': 256,
              'in_channels': 256,
              'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
              'loss_cls': {'loss_weight': 1.0, 'type': 'CrossEntropyLoss', 'use_sigmoid': True},
              'type': 'RPNHead'},
 'test_cfg': {'rcnn': {'max_per_img': 300,
                       'nms': {'iou_threshold': 0.6, 'type': 'nms'},
                       'score_thr': 0.0001},
              'rpn': {'max_per_img': 1000,
                      'min_bbox_size': 0,
                      'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                      'nms_pre': 1000}},
 'train_cfg': {'rcnn': [{'assigner': {'ignore_iof_thr': -1,
                                      'match_low_quality': False,
                                      'min_pos_iou': 0.5,
                                      'neg_iou_thr': 0.5,
                                      'perm_repeat_gt_cfg': {'iou_thr': 0.7,
                                                             'perm_range': 0.01},
                                      'pos_iou_thr': 0.5,
                                      'type': 'MaxIoUAssigner'},
                         'debug': False,
                         'pos_weight': -1,
                         'sampler': {'add_gt_as_proposals': True,
                                     'neg_pos_ub': -1,
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'type': 'RandomSampler'}},
                        {'assigner': {'ignore_iof_thr': -1,
                                      'match_low_quality': False,
                                      'min_pos_iou': 0.6,
                                      'neg_iou_thr': 0.6,
                                      'perm_repeat_gt_cfg': {'iou_thr': 0.7,
                                                             'perm_range': 0.01},
                                      'pos_iou_thr': 0.6,
                                      'type': 'MaxIoUAssigner'},
                         'debug': False,
                         'pos_weight': -1,
                         'sampler': {'add_gt_as_proposals': True,
                                     'neg_pos_ub': -1,
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'type': 'RandomSampler'}},
                        {'assigner': {'ignore_iof_thr': -1,
                                      'match_low_quality': False,
                                      'min_pos_iou': 0.7,
                                      'neg_iou_thr': 0.7,
                                      'perm_repeat_gt_cfg': {'iou_thr': 0.7,
                                                             'perm_range': 0.01},
                                      'pos_iou_thr': 0.7,
                                      'type': 'MaxIoUAssigner'},
                         'debug': False,
                         'pos_weight': -1,
                         'sampler': {'add_gt_as_proposals': True,
                                     'neg_pos_ub': -1,
                                     'num': 512,
                                     'pos_fraction': 0.25,
                                     'type': 'RandomSampler'}}],
               'rpn': {'allowed_border': 0,
                       'assigner': {'ignore_iof_thr': -1,
                                    'match_low_quality': True,
                                    'min_pos_iou': 0.3,
                                    'neg_iou_thr': 0.3,
                                    'pos_iou_thr': 0.7,
                                    'type': 'MaxIoUAssigner'},
                       'debug': False,
                       'pos_weight': -1,
                       'sampler': {'add_gt_as_proposals': False,
                                   'neg_pos_ub': -1,
                                   'num': 256,
                                   'pos_fraction': 0.5,
                                   'type': 'RandomSampler'}},
               'rpn_proposal': {'max_per_img': 2000,
                                'min_bbox_size': 0,
                                'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                                'nms_pre': 4000}},
 'type': 'CascadeRCNN'}
work_dir = 'work_dirs/v3det_cascade_baseline'
